return {}

-- return require('packer').startup(function(use)
--   use 'wbthomason/packer.nvim'
--   use {
--     'nvim-lualine/lualine.nvim',
--     requires = { 'nvim-tree/nvim-web-devicons', opt = true }
--   }
--   use 'nvim-lua/plenary.nvim'
--   use 'nvim-treesitter/nvim-treesitter'
--   use 'nvim-telescope/telescope.nvim'
--   use 'mfussenegger/nvim-dap'
--   use 'scalameta/nvim-metals'
-- end)

-- Lazy
-- plugins = {
--   "folke/neodev.nvim",
--   "folke/which-key.nvim",
--   { "folke/neoconf.nvim", cmd = "Neoconf" },
--   'nvim-lua/plenary.nvim',
--   'nvim-treesitter/nvim-treesitter',
--   'nvim-telescope/telescope.nvim',
--   'mfussenegger/nvim-dap',
--   'scalameta/nvim-metals',
-- }

-- return {
--   "folke/neodev.nvim",
--   "folke/which-key.nvim",
--   { "folke/neoconf.nvim", cmd = "Neoconf" },
-- }


--vim.cmd("colorscheme aura-dark")
--
--local tokyonight = require("lualine.themes.tokyonight")
--require("lualine").setup {
--  options = {
--    theme = tokyonight
--  }
--}
--require("telescope").setup()
--require("telescope").load_extension "file_browser"
--require("bufferline").setup()
--require("nvim-web-devicons").setup()
--
--local builtin = require('telescope.builtin')
--vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
--vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
--vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
--vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
--
---- Telescope file browser
---- Standard
---- vim.api.nvim_set_keymap(
----   "n",
----   "<space>fb",
----   ":Telescope file_browser<CR>",
----   { noremap = true }
---- )
---- Open file_browser with the path of the current buffer
--vim.api.nvim_set_keymap("n", "<space>.", ":Telescope file_browser path=%:p:h select_buffer=true<CR>", { noremap = true })
--
---- Buffer navigation
--vim.api.nvim_set_keymap("n", "gt", ":bn<CR>", { noremap = true })
--vim.api.nvim_set_keymap("n", "gT", ":bp<CR>", { noremap = true })
--
--require("nvim-tree").setup({
--  sort = {
--    sorter = "case_sensitive",
--  },
--  view = {
--    width = 30,
--  },
--  renderer = {
--    group_empty = true,
--  },
--  filters = {
--    dotfiles = true,
--  },
--})
--
--vim.api.nvim_set_keymap(
--  "n",
--  "T",
--  ":NvimTreeToggle<CR>",
--  { noremap = true }
--)
